name: Build & Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ios-build:
    name: 🧱 Build iOS App (frontend)
    runs-on: macos-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Resolve Swift Packages
        run: xcodebuild -resolvePackageDependencies -project ThePunch.xcodeproj

      - name: Build App
        run: |
          xcodebuild \
            -project ThePunch.xcodeproj \
            -scheme ThePunch \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.0' \
            clean build | xcpretty

      - name: Run Unit Tests (if present)
        run: |
          xcodebuild test \
            -project ThePunch.xcodeproj \
            -scheme ThePunch \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.0' \
            | xcpretty

  backend-test:
    name: 🧩 Backend (Node.js)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test || echo "no tests yet!"
